name: On pull request

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  web_lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install -g yarn
      - run: yarn install
        working-directory: ./web
      - name: Lint
        run: yarn lint
        working-directory: ./web

  web_build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install -g yarn
      - run: yarn install
        working-directory: ./web
      - name: Build
        run: yarn build
        working-directory: ./web

  web_test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - run: npm install -g yarn
      - run: yarn install
        working-directory: ./web
      - name: Test
        run: yarn test
        working-directory: ./web
